### ISSUE TITLE
Dutch radars: change in nominal timestamp causes visualisation failure

### ISSUE THREAD

**Issue by mrtnrey** [inbo/crow#170] opened 2022-09-29 10:31 UTC
The Dutch radars (Herwijnen=NLHRW, Den Helder=NLDHL) are unavailable in the visualisation since 2022-08-29.
However, the source data are produced; see e.g. https://opendata.meteo.be/ftp/observations/radar/vbird/nlhrw/2022/

A quick check revealed the cause: the nominal timestamp of the Dutch radar shifted one minute, i.e.:
HH:05 became HH:06
HH:10 became HH:11
See the source file https://opendata.meteo.be/ftp/observations/radar/vbird/nlhrw/2022/nlhrw_vpts_20220829.txt
at around 11:10 UTC that day.

As a consequence, the CROW visualisation fails...

The timestamp is read from the source HDF radar file so a quick fix on the side of the vpts generation is not possible imo.

@peterdesmet any ideas to implement a fix? Tnx!

**Comment by peterdesmet** [comment] 2022-10-03 07:18
@niconoe any idea what the cause might be? @stijnvanhoey and I can then attempt to fix it.

**Comment by stijnvanhoey** [comment] 2022-10-10 15:17
I had a look and the 'origin' of the issue is how the 'automatic downsampling' (by filtering out) as defined in https://github.com/inbo/crow/blob/main/src/components/Home.vue#L602 is setup at the momen:
- An empty data object is defined (see https://github.com/inbo/crow/blob/main/src/components/Home.vue#L538-L568) with the expected datetimes defined based on the [apptemporalresolution](https://github.com/inbo/crow/blob/main/src/components/Home.vue#L566) 
- when new data is coming in, the raw data rows with a matching datetime are retained and others are dropped (i.e. downsampling the data by filtering). 

_(Note, this makes the approach very effective int terms of performance as half of the data is directly dropped before any further processing)._ 

For example, when the data has a 5min resolution, 00:00, 00:05, 00:10... and the temporal resolution of the app is 10min, the data used for the visualizations is 00:00, 00:10 (dropping 00:05). As dutch radars has data rows 00:01, 00:06, 00:11, no data is retained (and no error is raised).

So, who to fix

1. Adjust the incoming timestamp on the incoming data-file adding a rounding https://github.com/inbo/crow/blob/main/src/helpers.ts#L163:
    ```javascript
    function roundNearest(num: number, resolution: number) {
      "Round to nearest resolution"
      return Math.round(num / resolution) * resolution;
    }
    datetime: roundNearest(moment.utc(row.substring(0, 13), "YYYYMMDD HHmm").valueOf(), 5 * 60 * 1000),
    ```
    This is fine if we know that the data will never have a resolution lower than 5minutes(!). It probably will work on 1min data resolution with 10min app resolution, but multiple incoming data records will get the same (rounded) timestamp and the setter would just re-assign each of these which is not ideal...).  See https://github.com/inbo/crow/pull/174 for the PR.
2. refactor the `storeDataRow`, but not yet sure how. E.g. looking for 'closest timestamp' instead of match will have a huge performance loss. Other option is to refactor the whole concept of the prefilled object (with predefined datetimes), but this is a much larger refactoring which we need to check if ok time-wise.

**Comment by niconoe** [comment] 2022-10-11 07:02
Just saw the notification... @stijnvanhoey's analysis seems perfect at first look. Indeed, I'm not sure what would be the best approach without spending time in it but once we think about it, this 5-minutes downsampling seems quite rigid (but it didn't bite us before now). I guess refactoring the `storeDataRow` would be ideal, but it's indeed a large change. You're also correct to be concerned about performance: CROW is quite heavy on the browser and I remember having to be careful about that from the beginning.

**Comment by mrtnrey** [comment] 2022-10-11 07:03
"data will never have a resolution lower than 5minutes" → I don't think it'll be the case soon, so this solution seems fine to me.

You could alternatively consider a "Floor" function of "Round" to obtain a 5-min timestep. This avoids collision between (rare but possible) late radar file arrivals.
See e..g. this hypothetical case
<ins>With Round</ins>
timestamp at 00:08  → 00:10
next timestamp at 00:11 → 00:10
<ins>With Floor</ins>
timestamp at 00:08  → 00:05
next timestamp at 00:11 → 00:10
But in practise I don't think this will happen very often so the choice between Floor/Round is not really important.

**Comment by stijnvanhoey** [comment] 2022-10-11 09:30
> You could alternatively consider a "Floor" function of "Round" to obtain a 5-min timestep. 

Indeed, valid point; I updated the PR, https://github.com/inbo/crow/pull/174

**Comment by peterdesmet** [comment] 2022-10-13 15:42
@stijnvanhoey can you clarify with an example why a “that the data will never have a resolution lower than 5minutes” is a requirement?

Otherwise, fine with using/keeping the approach to keep client processing as light as possible.

**Comment by stijnvanhoey** [comment] 2022-10-13 18:30
What currently happens for non-dutch radars:
- Data comes in on interval of 5min, e.g. 2022-10-10 00:00, 2022-10-10 00:05, 2022-10-10 00:10, 2022-10-10 00:15,...
- Application shows data on interval of 10min (configuration):
  - An empty js object is created with the timestamps 2022-10-10 00:00, 2022-10-10 00:10,...
  - Each line of the data is read and if there is a match the data is retained, i.e. 2022-10-10 00:00, 2022-10-10 00:10 are kept; in other words 2022-10-10 00:05, 2022-10-10 00:15,... are filtered out

What currently happens for the dutch radars:
- Data comes in on interval of 5min but with minute lag, e.g. 2022-10-10 00:01, 2022-10-10 00:06, 2022-10-10 00:11, 2022-10-10 00:16,...
- Application shows data on interval of 10min (configuration):
  - An empty js object is created with the timestamps 2022-10-10 00:00, 2022-10-10 00:10,...
  - Each line of the data is read and if there is a match the data is retained, i.e. all data is filtered out (no match)

What the PR with the 5min floor does for the dutch radars:
- Data comes in on interval of 5min but with minute lag e.g. 2022-10-10 00:01, 2022-10-10 00:06, 2022-10-10 00:11, 2022-10-10 00:16,...
- Application shows data on interval of 10min (configuration):
  - An empty js object is created with the timestamps 2022-10-10 00:00, 2022-10-10 00:10,...
  - Each line of the data is read and if there is a match _after floor to with 5min resolution_the data is retained, i.e.  `floor(2022-10-10 00:01, 5min)`=2022-10-10 00:00, `floor(2022-10-10 00:11, 5min)`=2022-10-10 00:10 are retained

What the PR with the 5min floor does for the a 1-min interval radar
- Data comes in on interval of 1min e.g. 2022-10-10 00:00, 2022-10-10 00:01, 2022-10-10 00:02, 2022-10-10 00:03, 2022-10-10 00:04, 2022-10-10 00:05, 2022-10-10 00:06...
- Application shows data on interval of 10min (configuration):
  - An empty js object is created with the timestamps 2022-10-10 00:00, 2022-10-10 00:10,...
  - Each line of the data is read and if there is a match _after floor to with 5min resolution_the data is retained, i.e.  `floor(2022-10-10 00:00, 5min)`=2022-10-10 00:00, `floor(2022-10-10 00:01, 5min)`=2022-10-10 00:00, `floor(2022-10-10 00:02, 5min)`=2022-10-10 00:00, `floor(2022-10-10 00:03, 5min)`=2022-10-10 00:00, `floor(2022-10-10 00:04, 5min)`=2022-10-10 00:00 all match with the timestamp 2022-10-10 00:00; hence the value in the prepared js object at 2022-10-10 00:00 is 4 times overwritten ([reset](https://github.com/inbo/crow/blob/main/src/components/Home.vue#L608-L611) via [this loop](https://github.com/inbo/crow/blob/main/src/components/Home.vue#L645-L646)). Actually timestamp 2022-10-10 00:04 will be used in the app. Expected behavior would be 2022-10-10 00:00 retained and others filtered out.

Hence - probably it will work - but not with the expected behavior.

**Comment by peterdesmet** [comment] 2022-10-17 12:39
I'd like an approach that is generic: we want to reuse it for data that can come in at any resolution.

2 questions:

1. Is the approach to then always floor? Or is flooring conditional?
2. Why are we flooring to a resolution (5min) that is _not_ the resolution of the app (10min)? Is that to avoid groups of duplicate timestamps that are too big (and thus many overwrites)?

I'm wondering if an approach would work like:

1. Always floor
2. Always take the first match (no overwrites)

**Comment by peterdesmet** [comment] 2022-10-17 14:14
Yes, I like that approach. Easy to explain too: data is floored to resolution of app, first row is selected.

**Comment by stijnvanhoey** [comment] 2022-10-17 14:58
> Yes, I like that approach. Easy to explain too: data is floored to resolution of app, first row is selected.

[Draft implementation done](https://github.com/inbo/crow/pull/174/commits/92f08a78d3ef46a613d369144f524089bb85d24a); I'll just have to do some double checks (not sure if this properly handles all the heights) and try to translate this in unit test as well.

**Comment by stijnvanhoey** [comment] 2022-10-17 15:15
@peterdesmet while running the app with the new implementation, one other issue in terms of implementation need to be tackled. Let's take the example of the 1min data:
- 2022-10-10 00:00 with height 2600m has no data (Nan in the txt-file)
- 2022-10-10 00:01 with height 2600m actually has data

With the (rather naive) current implementation, the value of 2600m will be filled in when passing the line with 2022-10-10 00:01 & 2600m, this is not the first line so with respect to 
> data is floored to resolution of app, first row is selected.

I should update the implementation so it can handle this situation and always takes the first row (even though this is a Nan)?

**Comment by stijnvanhoey** [comment] 2022-10-17 19:32
@peterdesmet  I landed with an implementation that fulfills the requirement:

> data is floored to resolution of app, first row is selected.

(_note, it is not really 1 row, but N-heights rows, as each row contains 1 height_)

See https://github.com/inbo/crow/pull/174/commits/2efeedf2006385f10b15a9f25200bc3c11b67fdb The filterinf of the records is now on earlier level and combined with the Nan-filtering (which overcomes the comment in https://github.com/inbo/crow/issues/170#issuecomment-1281032917). It actually does hurt the performance a bit with the additional groupby, can you have a check if this is still ok?

**Comment by peterdesmet** [comment] 2022-10-18 06:44
>  It actually does hurt the performance a bit with the additional groupby, can you have a check if this is still ok?

Not sure how to benchmark this... you mean locally vs the current online version?

**Comment by stijnvanhoey** [comment] 2022-10-18 08:21
> Not sure how to benchmark this... you mean locally vs the current online version?

I asked as I'm not sure how you benchmarked this before (I have no experience with [vue profiling](https://vuejs.org/guide/best-practices/performance.html#profiling-options)). Fact is, the operation groups/apply (cfr. map-reduce) the entire `dayData` object instead of direct filtering, so there will be 'some' slow-down.

**Comment by peterdesmet** [comment] 2022-10-18 08:32
I'm guessing it will be ok ... and has the advantage that it is a flexible and correct implementation.

**Comment by stijnvanhoey** [comment] 2022-10-24 21:25
@peterdesmet unit tests added, ready for review (& deployment)

**Comment by peterdesmet** [comment] 2022-10-25 08:37
#174 is now merged and new version of app should be deployed at: https://inbo.github.io/crow/

Todo:

- [ ] Verify issue is resolved for Dutch radars
- [ ] Remove Swiss radar `Albis` (this was a test and should not be displayed on meteo.be/birddetection) see
- [ ] Bump version number to v1.3
- [ ] Deploy at meteo.be

**Comment by mrtnrey** [comment] 2022-11-23 14:34
Hi @peterdesmet, any progress on you todo list?
Concerning the Dutch radars, the issue seems to be solved, so the first item: :heavy_check_mark: 
The other things seem to be rather small. Please let me know when we can deploy at meteo.be. Tnx!

**Comment by stijnvanhoey** [comment] 2022-11-28 14:08
@mrtnrey All ready to deploy version 1.3 to meteo.be

**Comment by peterdesmet** [comment] 2022-11-28 14:10
@mrtnrey You can download the code to deploy at https://github.com/inbo/crow/releases/tag/v1.3

**Comment by peterdesmet** [comment] 2023-03-18 15:00
@mrtnrey I notice this issue still remains at meteo.be/birddetection. Is it possible to deploy the latest version of crow there?

**Comment by mrtnrey** [comment] 2023-03-29 13:43
@peterdesmet release v1.3 deployed this afternoon on meteo.be/birddetection 🥳

**Comment by peterdesmet** [comment] 2023-03-29 13:49
Excellent! I'm sure @hvangasteren will be very happy to know that [Dutch weather radars can be viewed again on CROW](https://www.meteo.be/services/birdDetection/#/?radar=nlhrw&date=2023-03-14&interval=72&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en)

**Closed by peterdesmet** 2023-03-29 13:49 UTC

**Comment by hvangasteren** [comment] 2023-03-29 14:02
Hi great sw guys! Yes, this is awesome Thanks Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Peter Desmet ***@***.***> Datum: 29-03-2023  15:49  (GMT+01:00) Aan: inbo/crow ***@***.***> Cc: Hans van Gasteren ***@***.***>, Mention ***@***.***> Onderwerp: Re: [inbo/crow] Dutch radars: change in nominal timestamp causes visualisation failure (Issue #170) 
Excellent! I'm sure @hvangasteren will be very happy to know that Dutch weather radars can be viewed again on CROW
